# Generated by Django 3.2.9 on 2022-12-06 15:47

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=64, verbose_name=flights.models.Airport),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=64, verbose_name=flights.models.Airport),
        ),
    ]
